[CmdletBinding()]
param(
    [ValidateSet("Debug", "Release")]
    [string]$Configuration = "Release",
    [switch]$SkipSmokeTest
)

$ErrorActionPreference = "Stop"

$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$harnessRoot = (Resolve-Path (Join-Path $scriptRoot "..")).Path
$repoRoot = (Resolve-Path (Join-Path $harnessRoot "..\..")).Path
$manifestPath = Join-Path $harnessRoot "Cargo.toml"
$profileDir = if ($Configuration -eq "Release") { "release" } else { "debug" }
$cargoArgs = @(
    "build",
    "-p",
    "splcw-operator-gui",
    "--manifest-path",
    $manifestPath
)
if ($Configuration -eq "Release") {
    $cargoArgs += "--release"
}

$builtExe = Join-Path $harnessRoot "target\$profileDir\splcw-operator-gui.exe"
$distRoot = Join-Path $repoRoot "artifacts\ultimentality-pilot\operator\dist"
$distExe = Join-Path $distRoot "AGRO Harness Operator.exe"
$distReadme = Join-Path $distRoot "README.txt"
$readmeBody = @"
AGRO Harness Operator package

This folder is generated by:
  ultimentality-pilot/harness/scripts/package-operator-gui.ps1

Launch directly:
  AGRO Harness Operator.exe

Or use the checked-in launcher:
  ultimentality-pilot/harness/Launch AGRO Harness Operator.cmd

The operator uses:
  artifacts/ultimentality-pilot/operator/

Codex CLI is the primary operator engine.
OAuth overrides and provider fallback path hints can be placed in:
  artifacts/ultimentality-pilot/operator/operator.env

Supported names:
  SPLCW_OPENAI_CODEX_OAUTH_CLIENT_ID
  OPENAI_CODEX_OAUTH_CLIENT_ID
  SPLCW_OPENAI_API_OAUTH_CLIENT_ID
  OPENAI_API_OAUTH_CLIENT_ID
  SPLCW_OPENAI_OAUTH_CLIENT_ID
  OPENAI_OAUTH_CLIENT_ID
  OPENCLAW_STATE_DIR
  OPENCLAW_AGENT_DIR

Process environment variables still override operator.env when both are present.
"@

Write-Host "Building splcw-operator-gui ($Configuration)..."
& cargo @cargoArgs
if ($LASTEXITCODE -ne 0) {
    exit $LASTEXITCODE
}

if (-not (Test-Path $builtExe)) {
    throw "Expected built executable not found: $builtExe"
}

New-Item -ItemType Directory -Force -Path $distRoot | Out-Null
Copy-Item -LiteralPath $builtExe -Destination $distExe -Force
Set-Content -LiteralPath $distReadme -Value $readmeBody -Encoding UTF8

if (-not $SkipSmokeTest) {
    Push-Location $repoRoot
    try {
        & $distExe --smoke-test
        if ($LASTEXITCODE -ne 0) {
            exit $LASTEXITCODE
        }
    }
    finally {
        Pop-Location
    }
}

Write-Host "Packaged operator GUI:"
Write-Host "  $distExe"
